name: CI/CD for Vue.js Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.USER }}
          EC2_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_PRIVATE_KEY" > private-key.pem
          chmod 600 private-key.pem
          mkdir -p ~/.ssh
          ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts        
          
          
          # Deploy the files using SCP
          scp -o StrictHostKeyChecking=no -i private-key.pem -r dist/* $EC2_USER@$EC2_HOST:/var/www/html         
